services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
#    environment:
#      - DISABLE_PASSWORD_AUTH=true
    ports:
      - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data

