version: '3.8'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - excalidraw_data:/usr/src/app/storage
    restart: unless-stopped

volumes:
  excalidraw_data:
