version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000  # Change this to your user ID
      - PGID=1000  # Change this to your group ID
      - TZ=Pacific/Auckland  # Set your timezone
    ports:
      - 80:80  # Expose the web UI on port 8080
    restart: unless-stopped
    volumes:
      - /glusterfs:/srv #Change to match your directory
      - ./filebrowser/filebrowser.db:/database/filebrowser.db #Change to match your directory
      - ./filebrowser/settings.json:/config/settings.json #Change to match your directory




