version: '3.2'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"  # Grafana port (host:container)
    volumes:
 #     - ~/grafana/data:/var/lib/grafana  # Persist Grafana data
 #     - ~/grafana/config:/etc/grafana    # Custom configuration files
#      - ~/grafana/dashboards/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
#      - ~/grafana/dashboards/dashboards:/var/lib/grafana/dashboards
#      - ~/grafana/config/:/etc/grafana/grafana.ini
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-volume:/var/lib/influxdb

    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_CONTENT_SECURITY_POLICY="script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'none'; frame-src 'self' https://test.youro>
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  grafana-volume:
    external: true
