services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"  # Map host port 11434 to container port 11434
    pull_policy: always
    tty: true
    restart: unless-stopped

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "3001:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ollama-webui:/app/backend/data
    restart: always

volumes:
  ollama: {}
  ollama-webui: {}

