version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Pacific/Auckland'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: 'SECUREPASSWORD'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
