services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: ${HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./syncthing-config:/var/syncthing/config
      - ./syncthing-data:/var/syncthing/data
      - /rpifs/fs:/mnt/shared_data:rw
    ports:
      - "8384:8384"  # Web UI
      - "22000:22000"  # TCP file transfers
      - "22000:22000/udp"  # QUIC file transfers
      - "21027:21027/udp"  # Discovery broadcasts
    restart: unless-stopped
    networks:
      - syncthing_net

networks:
  syncthing_net:
    driver: bridge

